# site settings
title: Personal Webpage
subtitle: Vedant Choudhary
email: vedantc6@gmail.com
description: Looking for Summer 2019 internships<br /> in Machine Learning, Deep Learning and Software Development
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 136 George Street, 2nd Fl
city: New Brunswick
state: NJ
zip_code: 08901
country: United States of America
phone: (908) 930-2194

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/vedantc6
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/vedantc6/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
